consumes:
- application/x-www-form-urlencoded
definitions:
  SlackMessage:
    example:
      channel_id: Occaecati ut perspiciatis.
      channel_name: Aut aspernatur reiciendis.
      service_id: In totam optio.
      team_domain: Amet ut.
      team_id: Amet sunt id aut.
      text: Dolores dignissimos expedita itaque inventore.
      timestamp: 0.3135134
      token: Aliquam odio sunt ipsam.
      trigger_word: Et ad qui odio est dolorum culpa.
      user_id: Architecto aut quo et ut.
      user_name: Ipsam mollitia voluptatem ut sit explicabo.
    properties:
      channel_id:
        description: Channel ID
        example: Occaecati ut perspiciatis.
        type: string
      channel_name:
        description: Channel Name
        example: Aut aspernatur reiciendis.
        type: string
      service_id:
        description: Service ID
        example: In totam optio.
        type: string
      team_domain:
        description: Team Domain
        example: Amet ut.
        type: string
      team_id:
        description: Team ID
        example: Amet sunt id aut.
        type: string
      text:
        description: Message Text
        example: Dolores dignissimos expedita itaque inventore.
        type: string
      timestamp:
        description: Timestamp
        example: 0.3135134
        format: double
        type: number
      token:
        description: Slack Token
        example: Aliquam odio sunt ipsam.
        type: string
      trigger_word:
        description: Trigger Word
        example: Et ad qui odio est dolorum culpa.
        type: string
      user_id:
        description: User ID
        example: Architecto aut quo et ut.
        type: string
      user_name:
        description: User Name
        example: Ipsam mollitia voluptatem ut sit explicabo.
        type: string
    required:
    - text
    title: SlackMessage
    type: object
  VaaaaanquishBotMessage:
    description: VaaaaanquishBotMessage media type (default view)
    example:
      text: Esse et facere quia maiores.
    properties:
      text:
        description: Message Text
        example: Esse et facere quia maiores.
        type: string
    required:
    - text
    title: 'Mediatype identifier: application/vnd.vaaaaanquish.bot.message+json; view=default'
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  description: vaaaaanquish さんの名前を間違って発言すると訂正してくれる slack bot です
  title: vaaaaanquish-bot
  version: ""
paths:
  /:
    get:
      operationId: public#/
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download ./templates/index.tmpl.html
  /static/{filepath}:
    get:
      operationId: public#/static/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download ./static/
  /v1/slack/inbound:
    post:
      operationId: message#inbound
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/SlackMessage'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/VaaaaanquishBotMessage'
      schemes:
      - http
      summary: inbound message
      tags:
      - message
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
