// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/ikawaha/vaaaaanquish-bot/design
// --out=$(GOPATH)/src/github.com/ikawaha/vaaaaanquish-bot
// --version=v1.1.0-dirty
//
// API "vaaaaanquish-bot": Application Media Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import "github.com/goadesign/goa"

// VaaaaanquishBotMessage media type (default view)
//
// Identifier: application/vnd.vaaaaanquish.bot.message+json; view=default
type VaaaaanquishBotMessage struct {
	// Other Channel
	Channel *string `form:"channel,omitempty" json:"channel,omitempty" xml:"channel,omitempty"`
	// ICON Emoji
	IconEmoji *string `form:"icon_emoji,omitempty" json:"icon_emoji,omitempty" xml:"icon_emoji,omitempty"`
	// ICON URL
	IconURL *string `form:"icon_url,omitempty" json:"icon_url,omitempty" xml:"icon_url,omitempty"`
	// Message Text
	Text string `form:"text" json:"text" xml:"text"`
	// User Name
	Username *string `form:"username,omitempty" json:"username,omitempty" xml:"username,omitempty"`
}

// Validate validates the VaaaaanquishBotMessage media type instance.
func (mt *VaaaaanquishBotMessage) Validate() (err error) {
	if mt.Text == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "text"))
	}
	return
}
